# Generated by Django 3.0.2 on 2020-02-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_field', models.CharField(max_length=100, verbose_name='Demo Field')),
            ],
        ),
    ]
