# Generated by Django 3.0.2 on 2020-02-10 23:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_walk', models.BooleanField()),
                ('dog_breed', models.CharField(max_length=100)),
                ('dog_age', models.IntegerField()),
                ('dog_tricks', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Sit'), ('item_key2', 'Fetch'), ('item_key3', 'Stay'), ('item_key4', 'Roll Over')], max_length=39)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
